POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "changeme"
}

######

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "maria",
  "password": "guess",
  "roles": ["user","admin"]
}

######

GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTc3MDk3Nzk4MiwiZXhwIjoxNzcwOTc4MDQyfQ.dXMS_t_vTwF9C4cUu4TOpo-BYFLlhBcp5zGVMAXz1sw

######

GET http://localhost:3000/auth/public

######

GET http://localhost:3000/auth/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibWFyaWEiLCJyb2xlcyI6WyJ1c2VyIiwiYWRtaW4iXSwiaWF0IjoxNzcxMjMzMzQ1LCJleHAiOjE3NzEyMzM0MDV9.mCtuUwBvFa8rU78MJwMKeDvVh_S9ZfK35I_tXPV3SAU

###################
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "john",
  "lastName": "doe",
  "roles": ["user"]
}

#####
GET http://localhost:3000/users

##########
POST http://localhost:3000/jobs/producer-one
Content-Type: application/json

{
  "message": "Hello from P1"
}

#######
POST http://localhost:3000/jobs/producer-two
Content-Type: application/json

{
  "message": "Hello from P2"
}

######
GET http://localhost:3000/exemple-redis/1

################
GET http://localhost:3000/event/one

################
GET http://localhost:3000/event/two

#################
POST http://localhost:3000/file/file/pass-validation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="wallpaper.jpeg"
Content-Type: image/jpeg

< ./wallpaper.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#######

GET http://localhost:3000/file/download/wallpaper.jpeg
Accept: image/jpeg

#######

GET http://localhost:3000/file
Accept: application/json

#####
GET http://localhost:3000/users/axios

##### sur le nav
GET http://localhost:3000/sse
#####
GET http://localhost:3000/sse/sse